### PR TITLE
Javier

### PR DESCRIPTION
**Pull request by javierrojas96**
Pull Request for Github Submission of HW12.

### CODE REVIEW

**Comment by SLeviyang** [comment]
Javier, I need your .Rmd and .pdf file as well.

**Comment by javierrojas96** [comment]
I submitted .Rmd and .PDF to Dropbox. Did you want those files in GitHub as well as the pull request?

**Comment by SLeviyang** [comment]
Yes, commit .Rmd and .pdf to your repo and issue another pull request.
Thanks.

**Comment by SLeviyang** [comment]
You need to issue a pull request.

**Comment by SLeviyang** [comment]
Javier, ok great, merging.

**Comment by javierrojas96** [comment]
Excellent. Enjoyed the project.

**Comment by javierrojas96** [comment]
Pull requested with folder

**Pull request merged**
